#!/usr/bin/env python3
"""Audit an npm package and plan its publication through one of two auth modes.

``--auth-mode oidc`` generates a tokenless GitHub Actions trusted-publishing
workflow. ``--auth-mode bypass`` plans a local publish using a granular
(Bypass-2FA) ``NPM_TOKEN``. ``--auth-mode auto`` (default) picks ``oidc`` when a
GitHub repository resolves and ``bypass`` otherwise.

The command is read-only unless ``--write`` is supplied (oidc only). Registry
state can be overridden for deterministic tests; the default performs an
anonymous npm registry read. It never reads, writes, or prints npm credentials.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path
from typing import Any, Optional, Tuple


DEFAULT_REGISTRY = "https://registry.npmjs.org"
GENERATED_MARKER = "# Generated by lov-npm-publisher"
SEMVER_RE = re.compile(
    r"^(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)"
    r"(?:-[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?"
    r"(?:\+[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?$"
)


class AuditError(Exception):
    """Raised when local package inputs cannot form a safe plan."""


def read_json(path: Path) -> dict[str, Any]:
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise AuditError(f"package manifest not found: {path}") from exc
    except json.JSONDecodeError as exc:
        raise AuditError(f"invalid JSON in {path}: {exc}") from exc
    if not isinstance(data, dict):
        raise AuditError(f"expected an object in {path}")
    return data


def run_git(package_dir: Path, *args: str) -> str:
    result = subprocess.run(
        ["git", "-C", str(package_dir), *args],
        capture_output=True,
        text=True,
        check=False,
    )
    return result.stdout.strip() if result.returncode == 0 else ""


def github_repo(value: str) -> Optional[str]:
    text = value.strip()
    if text.startswith("git+"):
        text = text[4:]
    patterns = (
        r"^git@github\.com:([^/]+/[^/]+?)(?:\.git)?$",
        r"^ssh://git@github\.com/([^/]+/[^/]+?)(?:\.git)?$",
        r"^https?://github\.com/([^/]+/[^/]+?)(?:\.git)?/?$",
    )
    for pattern in patterns:
        match = re.match(pattern, text)
        if match:
            return match.group(1).removesuffix(".git")
    return None


def package_repository(package: dict[str, Any]) -> str:
    repository = package.get("repository", "")
    if isinstance(repository, str):
        return repository.strip()
    if isinstance(repository, dict):
        url = repository.get("url", "")
        return url.strip() if isinstance(url, str) else ""
    return ""


def resolve_repo(package_dir: Path, package: dict[str, Any]) -> Tuple[str, str, str]:
    remote = run_git(package_dir, "remote", "get-url", "origin")
    package_url = package_repository(package)
    remote_repo = github_repo(remote) if remote else None
    manifest_repo = github_repo(package_url) if package_url else None
    repo = remote_repo or manifest_repo
    if not repo:
        raise AuditError(
            "could not resolve a GitHub owner/repo from git origin or package.json repository"
        )
    return repo, remote, package_url


def validate_workflow_path(raw: str) -> Path:
    path = Path(raw)
    if path.is_absolute() or ".." in path.parts:
        raise AuditError("workflow path must be a safe relative path")
    if path.suffix not in {".yml", ".yaml"}:
        raise AuditError("workflow path must end in .yml or .yaml")
    if tuple(path.parts[:2]) != (".github", "workflows") or len(path.parts) != 3:
        raise AuditError("workflow must be directly under .github/workflows")
    return path


def package_manager(package_dir: Path, package: dict[str, Any]) -> str:
    if (package_dir / "pnpm-lock.yaml").is_file():
        return "pnpm"
    if (package_dir / "bun.lock").is_file() or (package_dir / "bun.lockb").is_file():
        return "bun"
    if (package_dir / "yarn.lock").is_file():
        return "yarn"
    if (package_dir / "package-lock.json").is_file() or (package_dir / "npm-shrinkwrap.json").is_file():
        return "npm"
    declared = package.get("packageManager") if isinstance(package, dict) else None
    if isinstance(declared, str) and "@" in declared:
        name = declared.split("@", 1)[0]
        if name in {"npm", "pnpm", "yarn", "bun"}:
            return name
    return "npm"


def install_steps(manager: str, package_dir: Path) -> list[str]:
    if manager == "pnpm":
        return ["      - run: corepack enable", "      - run: pnpm install --frozen-lockfile"]
    if manager == "yarn":
        return ["      - run: corepack enable", "      - run: yarn install --immutable"]
    if manager == "bun":
        return [
            "      - uses: oven-sh/setup-bun@v2",
            "      - run: bun install --frozen-lockfile",
        ]
    if (package_dir / "package-lock.json").is_file() or (package_dir / "npm-shrinkwrap.json").is_file():
        return ["      - run: npm ci"]
    return ["      - run: npm install"]


def workflow_text(
    package_name: str,
    access: str,
    manager: str,
    tag_pattern: str,
    package_dir: Path,
) -> str:
    install = "\n".join(install_steps(manager, package_dir))
    publish = "npm publish" + (" --access public" if access == "public" else "")
    return f"""{GENERATED_MARKER}
name: npm-publish

on:
  push:
    tags:
      - "{tag_pattern}"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: npm-publish-{package_name}
  cancel-in-progress: false

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"
          package-manager-cache: false
{install}
      - run: npm run build --if-present
      - run: npm run test --if-present
      - run: {publish}
"""


def inspect_existing_workflow(path: Path, expected: str) -> dict[str, Any]:
    if not path.is_file():
        return {
            "state": "missing",
            "oidc": False,
            "publish": False,
            "long_lived_secret": False,
            "matches_generated": False,
        }
    text = path.read_text(encoding="utf-8")
    secret_pattern = re.compile(
        r"NPM_TOKEN|NODE_AUTH_TOKEN|_authToken\s*=|secrets\.[A-Za-z0-9_]*NPM",
        re.IGNORECASE,
    )
    return {
        "state": "present",
        "oidc": "id-token: write" in text,
        "publish": bool(re.search(r"(?m)^\s*-\s+run:\s+.*\bnpm\s+publish\b", text)),
        "long_lived_secret": bool(secret_pattern.search(text)),
        "matches_generated": text == expected,
        "generated_by_skill": GENERATED_MARKER in text,
    }


def registry_metadata(registry: str, package_name: str) -> Tuple[str, Optional[dict[str, Any]], str]:
    encoded = urllib.parse.quote(package_name, safe="@")
    url = f"{registry.rstrip('/')}/{encoded}"
    request = urllib.request.Request(
        url,
        headers={"Accept": "application/json", "User-Agent": "lov-npm-publisher/0.1.0"},
    )
    try:
        with urllib.request.urlopen(request, timeout=10) as response:
            data = json.loads(response.read().decode("utf-8"))
        return "exists", data if isinstance(data, dict) else {}, url
    except urllib.error.HTTPError as exc:
        if exc.code == 404:
            return "missing", None, url
        return "unknown", None, f"{url} returned HTTP {exc.code}"
    except (urllib.error.URLError, TimeoutError, json.JSONDecodeError) as exc:
        return "unknown", None, f"{url} could not be verified: {exc}"


def forced_registry_state(state: str, registry: str, package_name: str) -> Tuple[str, Optional[dict[str, Any]], str]:
    if state == "auto":
        return registry_metadata(registry, package_name)
    return state, None, f"registry state forced to {state} for deterministic verification"


def write_workflow(path: Path, content: str, inspection: dict[str, Any], force: bool) -> str:
    if inspection["state"] == "present":
        if inspection["matches_generated"]:
            return "unchanged"
        equivalent = inspection["oidc"] and inspection["publish"] and not inspection["long_lived_secret"]
        if equivalent and not force:
            return "preserved-equivalent"
        if not force:
            raise AuditError(
                f"refusing to replace {path}: existing workflow is not the generated tokenless form; review it and use --force explicitly"
            )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return "written"


def local_token_state() -> dict[str, Any]:
    """Detect a local granular (Bypass-2FA) npm token without reading its value."""
    if os.environ.get("NPM_TOKEN"):
        return {"present": True, "source": "NPM_TOKEN environment variable"}
    npmrc = Path.home() / ".npmrc"
    if npmrc.is_file():
        text = npmrc.read_text(encoding="utf-8")
        if re.search(r"(?m)^(?://registry\.npmjs\.org/)?_authToken=", text):
            return {"present": True, "source": "~/.npmrc _authToken"}
    return {"present": False, "source": None}


def bypass_publish_command(access: str) -> str:
    access_flag = " --access public" if access == "public" else ""
    return f'npm publish{access_flag} --//registry.npmjs.org/:_authToken="${{NPM_TOKEN}}"'


def build_plan(args: argparse.Namespace) -> Tuple[dict[str, Any], str, Path]:
    package_dir = Path(args.package_dir).expanduser().resolve()
    package = read_json(package_dir / "package.json")
    name = package.get("name")
    version = package.get("version")
    if not isinstance(name, str) or not name.strip():
        raise AuditError("package.json requires a non-empty name")
    if name.startswith("@") and "/" not in name[1:]:
        raise AuditError("scoped package name must use @scope/name")
    if not isinstance(version, str) or not SEMVER_RE.fullmatch(version):
        raise AuditError("package.json version must be valid SemVer")
    if package.get("private") is True:
        raise AuditError("package.json has private=true; refuse to generate a public npm publish workflow")

    manager = package_manager(package_dir, package)
    publish_config = package.get("publishConfig", {})
    configured_access = publish_config.get("access") if isinstance(publish_config, dict) else None
    access = args.access or (configured_access if configured_access in {"public", "restricted"} else "public")

    repo: Optional[str] = None
    remote = ""
    package_url = ""
    try:
        repo, remote, package_url = resolve_repo(package_dir, package)
    except AuditError:
        repo, remote, package_url = None, "", ""
    has_repo = repo is not None

    workflow_relative = validate_workflow_path(args.workflow)
    workflow_path = package_dir / workflow_relative
    state, metadata, evidence = forced_registry_state(args.registry_state, args.registry, name)

    versions = metadata.get("versions", {}) if isinstance(metadata, dict) else {}
    exact_version_exists: Optional[bool]
    if state == "exists" and isinstance(metadata, dict) and isinstance(versions, dict):
        exact_version_exists = version in versions
    else:
        exact_version_exists = None

    resolved_mode = args.auth_mode
    if resolved_mode == "auto":
        resolved_mode = "oidc" if has_repo else "bypass"

    warnings: list[str] = []
    blockers: list[str] = []
    if access == "restricted":
        warnings.append("restricted access is not a public-package default; confirm the account supports private package publishing")
    if state == "unknown":
        blockers.append("npm registry state is unknown; do not publish until the registry read succeeds")
    if exact_version_exists is True:
        blockers.append(f"{name}@{version} already exists and npm versions are immutable")

    if state == "missing":
        lifecycle_state = "bootstrap_required"
    elif state == "exists":
        lifecycle_state = "package_exists"
    else:
        lifecycle_state = "registry_unknown"

    content = ""
    workflow: Optional[dict[str, Any]] = None
    trust_command: Optional[str] = None
    publish_command: Optional[str] = None
    token: Optional[dict[str, Any]] = None

    if resolved_mode == "oidc":
        if not has_repo:
            blockers.append(
                "oidc trusted publishing requires a GitHub repository; run from a GitHub repo or use --auth-mode bypass for local publishing"
            )
        else:
            content = workflow_text(name, access, manager, args.tag_pattern, package_dir)
            workflow = inspect_existing_workflow(workflow_path, content)
            if workflow["long_lived_secret"]:
                warnings.append("existing workflow references a long-lived npm credential")
            package_repo = github_repo(package_url) if package_url else None
            if not package_url:
                blockers.append("package.json repository.url is required for GitHub trusted publishing")
            elif package_repo != repo:
                blockers.append(
                    f"package.json repository resolves to {package_repo or 'non-GitHub'}, but release repo is {repo}"
                )
            trust_command = (
                f"npm trust github {name} --repo {repo} --file {workflow_relative.name} --allow-publish"
            )
        if state == "missing":
            next_steps = [
                "npm login",
                f"npm publish{' --access public' if access == 'public' else ''}",
                f"verify {name}@{version} from the npm registry",
            ]
            if trust_command:
                next_steps.append(trust_command)
        elif state == "exists":
            next_steps = ["verify or configure the exact trusted publisher binding"]
            if trust_command:
                next_steps.append(trust_command)
            next_steps.append(f"publish a new immutable version through {workflow_relative}")
        else:
            next_steps = ["retry the anonymous npm registry read before any publish action"]
    else:
        token = local_token_state()
        publish_command = bypass_publish_command(access)
        if not token["present"]:
            warnings.append(
                "no local NPM_TOKEN or ~/.npmrc _authToken found; provide a granular (Bypass-2FA) token before publishing"
            )
        next_steps = [
            f"publish using a granular NPM_TOKEN ({token['source'] or 'set NPM_TOKEN first'})",
            publish_command,
            f"verify {name}@{version} from the npm registry",
        ]

    plan = {
        "schema": "lov-npm-publisher/plan-v2",
        "package": {
            "name": name,
            "version": version,
            "access": access,
            "package_manager": manager,
            "repository": package_url,
        },
        "auth": {
            "requested": args.auth_mode,
            "mode": resolved_mode,
            "token": token,
            "publish_command": publish_command,
        },
        "github": {
            "repo": repo,
            "origin": remote,
            "workflow": str(workflow_relative),
        },
        "registry": {
            "url": args.registry,
            "state": state,
            "evidence": evidence,
            "exact_version_exists": exact_version_exists,
        },
        "workflow": workflow,
        "lifecycle_state": lifecycle_state,
        "trust_command": trust_command,
        "warnings": warnings,
        "blockers": blockers,
        "next_steps": next_steps,
    }
    return plan, content, workflow_path


def print_human(plan: dict[str, Any]) -> None:
    package = plan["package"]
    registry = plan["registry"]
    auth = plan["auth"]
    print(f"package: {package['name']}@{package['version']}")
    print(f"state: {plan['lifecycle_state']}  registry: {registry['state']}  auth: {auth['mode']}")
    print(f"repo: {plan['github']['repo']}  workflow: {plan['github']['workflow']}")
    for warning in plan["warnings"]:
        print(f"warning: {warning}")
    for blocker in plan["blockers"]:
        print(f"blocker: {blocker}")
    print("next:")
    for step in plan["next_steps"]:
        print(f"- {step}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("package_dir", nargs="?", default=".")
    parser.add_argument("--registry", default=DEFAULT_REGISTRY)
    parser.add_argument(
        "--registry-state",
        choices=("auto", "exists", "missing"),
        default="auto",
        help="override registry existence for deterministic tests",
    )
    parser.add_argument(
        "--auth-mode",
        choices=("auto", "oidc", "bypass"),
        default="auto",
        help="publish authentication: oidc (GitHub trusted publishing), bypass (granular NPM_TOKEN), or auto",
    )
    parser.add_argument("--workflow", default=".github/workflows/publish.yml")
    parser.add_argument("--tag-pattern", default="v*")
    parser.add_argument("--access", choices=("public", "restricted"))
    parser.add_argument("--write", action="store_true", help="write the workflow")
    parser.add_argument("--force", action="store_true", help="replace a reviewed existing workflow")
    parser.add_argument("--dry-run", action="store_true", help="guarantee no repository writes")
    parser.add_argument("--json", action="store_true", help="print a machine-readable plan")
    args = parser.parse_args()

    if args.write and args.dry_run:
        parser.error("--write and --dry-run are mutually exclusive")
    try:
        plan, content, workflow_path = build_plan(args)
        if args.write:
            if plan["auth"]["mode"] == "bypass":
                plan["write_state"] = "not-applicable"
            else:
                if any("repository.url" in item for item in plan["blockers"]):
                    raise AuditError("fix package repository metadata before writing the OIDC workflow")
                plan["write_state"] = write_workflow(
                    workflow_path, content, plan["workflow"], args.force
                )
        else:
            plan["write_state"] = "dry-run" if args.dry_run else "not-requested"
            if plan["auth"]["mode"] == "oidc":
                plan["workflow_preview"] = content
    except AuditError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    if args.json:
        print(json.dumps(plan, ensure_ascii=False, indent=2))
    else:
        print_human(plan)
        print(f"write: {plan['write_state']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
