#!/usr/bin/env python3
"""Move Claude desktop sessions from one signed-in account to another.

The desktop app files Code-tab sessions under
``claude-code-sessions/<account>/<org>/`` and Cowork sessions under
``local-agent-mode-sessions/<account>/<org>/``. Signing in with another
account only changes which folder the sidebar reads, so old sessions stay on
disk but disappear from view. This tool copies them into the target account
without touching the source, credentials, or app configuration.

Subcommands:
  scan       list accounts, orgs, session counts and transcript health
  migrate    plan (default) or --apply a copy from one account to another
  retention  ensure Cowork sessions keep transcripts (cleanupPeriodDays)
"""
from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path

UUID_RE = re.compile(r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$")
CODE_DIR = "claude-code-sessions"
COWORK_DIR = "local-agent-mode-sessions"
ARCHIVE_IDX = "archived-sessions.idx"
BACKLOG = Path("backlog") / "tasks.json"
SCHEDULED = "scheduled-tasks.json"
# Account-scoped Cowork support files worth carrying over when the target lacks them.
# Server caches (*-cache.json), debug and rpm are regenerated by the app.
COWORK_SUPPORT = ("spaces", "cowork_settings.json", "cowork_plugins")
CLI_DEFAULT_RETENTION = 30
DEFAULT_RETENTION = 3650


# ---------- paths and small helpers ----------

def default_data_dir() -> Path | None:
    env = os.environ.get("CLAUDE_DESKTOP_DATA_DIR")
    if env:
        return Path(env).expanduser()
    if sys.platform == "darwin":
        return Path.home() / "Library" / "Application Support" / "Claude"
    return None


def default_cli_dir() -> Path:
    return Path(os.environ.get("CLAUDE_CONFIG_DIR") or Path.home() / ".claude").expanduser()


def read_json(path: Path, default=None):
    try:
        with path.open(encoding="utf-8") as fh:
            return json.load(fh)
    except (OSError, ValueError):
        return default


def write_json_atomic(path: Path, data) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(prefix=".tmp-", dir=str(path.parent))
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            json.dump(data, fh, ensure_ascii=False, indent=2)
            fh.write("\n")
        os.replace(tmp, path)
    except BaseException:
        if os.path.exists(tmp):
            os.unlink(tmp)
        raise


def uuid_dirs(path: Path) -> list[str]:
    if not path.is_dir():
        return []
    return sorted(p.name for p in path.iterdir() if p.is_dir() and UUID_RE.match(p.name))


def iso(ms) -> str | None:
    if not isinstance(ms, (int, float)):
        return None
    return datetime.fromtimestamp(ms / 1000, tz=timezone.utc).strftime("%Y-%m-%d")


def session_files(folder: Path) -> list[Path]:
    if not folder.is_dir():
        return []
    return sorted(folder.glob("local_*.json"))


# ---------- discovery ----------

class Store:
    def __init__(self, data_dir: Path, cli_dir: Path):
        self.data_dir = data_dir
        self.cli_dir = cli_dir
        self.code_root = data_dir / CODE_DIR
        self.cowork_root = data_dir / COWORK_DIR
        self._transcripts: set[str] | None = None

    def transcripts(self) -> set[str]:
        if self._transcripts is None:
            ids: set[str] = set()
            projects = self.cli_dir / "projects"
            if projects.is_dir():
                for proj in projects.iterdir():
                    if proj.is_dir():
                        ids.update(f.stem for f in proj.glob("*.jsonl"))
            self._transcripts = ids
        return self._transcripts

    def current_account(self) -> str | None:
        cfg = read_json(self.data_dir / "config.json", {}) or {}
        return cfg.get("lastKnownAccountUuid")

    def accounts(self) -> list[str]:
        return sorted(set(uuid_dirs(self.code_root)) | set(uuid_dirs(self.cowork_root)))

    def orgs(self, account: str) -> list[str]:
        return sorted(set(uuid_dirs(self.code_root / account)) | set(uuid_dirs(self.cowork_root / account)))

    def emails(self) -> dict[str, str]:
        # Cowork session files keep the email of the account that created them, so
        # after a migration the same email shows up under two accounts; such an
        # inference is ambiguous and dropped. The CLI login is authoritative.
        inferred: dict[str, str] = {}
        for account in uuid_dirs(self.cowork_root):
            for org in uuid_dirs(self.cowork_root / account):
                for f in session_files(self.cowork_root / account / org)[:5]:
                    email = (read_json(f, {}) or {}).get("emailAddress")
                    if email:
                        inferred.setdefault(account, email)
                        break
        owners: dict[str, int] = {}
        for email in inferred.values():
            owners[email] = owners.get(email, 0) + 1
        found = {a: e for a, e in inferred.items() if owners[e] == 1}
        oauth = (read_json(Path.home() / ".claude.json", {}) or {}).get("oauthAccount") or {}
        if oauth.get("accountUuid") and oauth.get("emailAddress"):
            found[oauth["accountUuid"]] = oauth["emailAddress"]
        return found

    def has_transcript(self, meta: dict) -> bool:
        sid = meta.get("cliSessionId")
        return bool(sid) and sid in self.transcripts()

    def org_stats(self, account: str, org: str) -> dict:
        code_dir = self.code_root / account / org
        cowork_dir = self.cowork_root / account / org
        code = [read_json(f, {}) or {} for f in session_files(code_dir)]
        cowork_files = session_files(cowork_dir)
        cowork = [read_json(f, {}) or {} for f in cowork_files]
        stamps = [m.get("lastActivityAt") for m in code + cowork if isinstance(m.get("lastActivityAt"), (int, float))]
        archived = (read_json(code_dir / ARCHIVE_IDX, {}) or {}).get("archived") or []
        tasks = (read_json(code_dir / SCHEDULED, {}) or {}).get("scheduledTasks") or []
        cowork_without_retention = sum(
            1 for f in cowork_files
            if f.with_suffix("").is_dir() and retention_of(f.with_suffix("")) <= CLI_DEFAULT_RETENTION
        )
        return {
            "org": org,
            "code_sessions": len(code),
            "code_with_transcript": sum(1 for m in code if self.has_transcript(m)),
            "code_archived_idx": len(archived),
            "cowork_sessions": len(cowork),
            "cowork_default_retention": cowork_without_retention,
            "scheduled_tasks": len(tasks),
            "first_activity": iso(min(stamps)) if stamps else None,
            "last_activity": iso(max(stamps)) if stamps else None,
        }

    def resolve_account(self, token: str) -> str:
        if token == "current":
            cur = self.current_account()
            if not cur:
                raise SystemExit("error: config.json has no lastKnownAccountUuid; pass the account uuid explicitly")
            return cur
        accounts = self.accounts()
        if token in accounts:
            return token
        emails = self.emails()
        by_email = [a for a, e in emails.items() if e.lower() == token.lower()]
        if by_email:
            return by_email[0]
        prefix = [a for a in accounts if a.startswith(token.lower())]
        if len(token) >= 8 and len(prefix) == 1:
            return prefix[0]
        raise SystemExit(f"error: cannot resolve account '{token}'; run `scan` to list uuids")

    def resolve_target_org(self, account: str, org: str | None) -> str:
        if org:
            return org
        orgs = [o for o in self.orgs(account) if session_files(self.code_root / account / o)
                or session_files(self.cowork_root / account / o)]
        orgs = orgs or self.orgs(account)
        if len(orgs) == 1:
            return orgs[0]
        raise SystemExit(f"error: target account has {len(orgs)} orgs {orgs}; pass --to-org")


def retention_of(session_dir: Path) -> int:
    settings = read_json(session_dir / ".claude" / "settings.json", {}) or {}
    value = settings.get("cleanupPeriodDays")
    return value if isinstance(value, int) else CLI_DEFAULT_RETENTION


# ---------- scan ----------

def cmd_scan(store: Store, args) -> dict:
    emails = store.emails()
    current = store.current_account()
    cli_settings = read_json(store.cli_dir / "settings.json", {}) or {}
    report = {
        "data_dir": str(store.data_dir),
        "current_account": current,
        "cli_cleanup_period_days": cli_settings.get("cleanupPeriodDays", f"unset (default {CLI_DEFAULT_RETENTION})"),
        "accounts": [],
    }
    for account in store.accounts():
        report["accounts"].append({
            "account": account,
            "email": emails.get(account),
            "current": account == current,
            "orgs": [store.org_stats(account, org) for org in store.orgs(account)],
        })
    return report


def print_scan(report: dict) -> None:
    print(f"data_dir: {report['data_dir']}")
    print(f"CLI cleanupPeriodDays: {report['cli_cleanup_period_days']}")
    for acc in report["accounts"]:
        if not any(o["code_sessions"] or o["cowork_sessions"] or o["scheduled_tasks"] for o in acc["orgs"]):
            continue
        tag = "  <- current" if acc["current"] else ""
        print(f"\naccount {acc['account']} {acc['email'] or '(email unknown)'}{tag}")
        for o in acc["orgs"]:
            if not (o["code_sessions"] or o["cowork_sessions"] or o["scheduled_tasks"]):
                continue
            span = f"{o['first_activity']} ~ {o['last_activity']}" if o["first_activity"] else "-"
            print(f"  org {o['org']}  {span}")
            print(f"    code: {o['code_sessions']} (transcript ok {o['code_with_transcript']}, archived {o['code_archived_idx']})"
                  f"  cowork: {o['cowork_sessions']} (default 30d retention {o['cowork_default_retention']})"
                  f"  scheduled tasks: {o['scheduled_tasks']}")


# ---------- migrate ----------

def ensure_retention(session_dir: Path, days: int, apply: bool) -> bool:
    if retention_of(session_dir) >= days:
        return False
    if apply:
        path = session_dir / ".claude" / "settings.json"
        settings = read_json(path, {}) or {}
        settings["cleanupPeriodDays"] = days
        write_json_atomic(path, settings)
    return True


def migrate_code(store: Store, src: Path, dst: Path, include_orphans: bool, apply: bool) -> dict:
    out = {"copied": 0, "already_present": 0, "orphans_skipped": 0, "orphans_copied": 0,
           "archived_added": 0, "backlog_added": 0, "scheduled_tasks_not_moved": 0}
    present = set()
    for f in session_files(src):
        target = dst / f.name
        if target.exists():
            out["already_present"] += 1
            present.add(f.stem)
            continue
        orphan = not store.has_transcript(read_json(f, {}) or {})
        if orphan and not include_orphans:
            out["orphans_skipped"] += 1
            continue
        out["orphans_copied" if orphan else "copied"] += 1
        present.add(f.stem)
        if apply:
            dst.mkdir(parents=True, exist_ok=True)
            shutil.copy2(f, target)

    src_idx = read_json(src / ARCHIVE_IDX, {}) or {}
    dst_idx = read_json(dst / ARCHIVE_IDX, {"v": 1, "archived": []}) or {"v": 1, "archived": []}
    have = list(dst_idx.get("archived") or [])
    add = [sid for sid in src_idx.get("archived") or [] if sid in present and sid not in have]
    out["archived_added"] = len(add)
    if add and apply:
        dst_idx["archived"] = have + add
        dst_idx.setdefault("v", src_idx.get("v", 1))
        write_json_atomic(dst / ARCHIVE_IDX, dst_idx)

    src_bl = read_json(src / BACKLOG, {}) or {}
    if src_bl.get("items"):
        dst_bl = read_json(dst / BACKLOG, {"version": src_bl.get("version", 1), "items": []})
        ids = {i.get("id") for i in dst_bl.get("items") or []}
        new = [i for i in src_bl["items"] if i.get("id") not in ids]
        out["backlog_added"] = len(new)
        if new and apply:
            dst_bl["items"] = list(dst_bl.get("items") or []) + new
            write_json_atomic(dst / BACKLOG, dst_bl)

    out["scheduled_tasks_not_moved"] = len((read_json(src / SCHEDULED, {}) or {}).get("scheduledTasks") or [])
    return out


def migrate_cowork(src: Path, dst: Path, days: int, apply: bool) -> dict:
    out = {"copied": 0, "already_present": 0, "retention_set": 0,
           "cwd_inside_source": 0, "support_copied": []}
    for f in session_files(src):
        sdir = f.with_suffix("")
        tjson, tdir = dst / f.name, dst / sdir.name
        if tjson.exists() or tdir.exists():
            out["already_present"] += 1
            if tdir.is_dir() and ensure_retention(tdir, days, apply):
                out["retention_set"] += 1
            continue
        out["copied"] += 1
        if str(src) in str((read_json(f, {}) or {}).get("cwd") or ""):
            out["cwd_inside_source"] += 1
        if apply:
            dst.mkdir(parents=True, exist_ok=True)
            if sdir.is_dir():
                shutil.copytree(sdir, tdir, symlinks=True)
            shutil.copy2(f, tjson)
        if (tdir.is_dir() or sdir.is_dir()) and ensure_retention(tdir if apply else sdir, days, apply):
            out["retention_set"] += 1
    for name in COWORK_SUPPORT:
        s, t = src / name, dst / name
        if not s.exists():
            continue
        if s.is_dir():
            for child in sorted(s.iterdir()):
                if not (t / child.name).exists():
                    out["support_copied"].append(f"{name}/{child.name}")
                    if apply:
                        t.mkdir(parents=True, exist_ok=True)
                        (shutil.copytree(child, t / child.name, symlinks=True) if child.is_dir()
                         else shutil.copy2(child, t / child.name))
        elif not t.exists():
            out["support_copied"].append(name)
            if apply:
                dst.mkdir(parents=True, exist_ok=True)
                shutil.copy2(s, t)
    return out


def cmd_migrate(store: Store, args) -> dict:
    source = store.resolve_account(args.source)
    target = store.resolve_account(args.target)
    to_org = store.resolve_target_org(target, args.to_org)
    from_orgs = [args.from_org] if args.from_org else store.orgs(source)
    if source == target and to_org in from_orgs:
        raise SystemExit("error: source and target are the same account/org")
    report = {"mode": "apply" if args.apply else "plan", "source": source, "target": target,
              "target_org": to_org, "retention_days": args.retention_days, "orgs": []}
    for org in from_orgs:
        entry = {"org": org}
        if not args.no_code:
            entry["code"] = migrate_code(store, store.code_root / source / org,
                                         store.code_root / target / to_org,
                                         args.include_orphans, args.apply)
        if not args.no_cowork:
            entry["cowork"] = migrate_cowork(store.cowork_root / source / org,
                                             store.cowork_root / target / to_org,
                                             args.retention_days, args.apply)
        report["orgs"].append(entry)
    cli_settings = read_json(store.cli_dir / "settings.json", {}) or {}
    report["cli_cleanup_period_days"] = cli_settings.get("cleanupPeriodDays")
    return report


def print_migrate(report: dict) -> None:
    verb = "copied" if report["mode"] == "apply" else "to copy"
    print(f"[{report['mode']}] {report['source']} -> {report['target']} (org {report['target_org']})")
    for o in report["orgs"]:
        c, w = o.get("code"), o.get("cowork")
        if c and any(v for v in c.values()):
            print(f"  code  from org {o['org']}: {verb} {c['copied']}, already present {c['already_present']}, "
                  f"orphans skipped {c['orphans_skipped']} / copied {c['orphans_copied']}, "
                  f"archived +{c['archived_added']}, backlog +{c['backlog_added']}")
            if c["scheduled_tasks_not_moved"]:
                print(f"    note: {c['scheduled_tasks_not_moved']} scheduled task(s) are not migrated; recreate them in the target account")
        if w and (w["copied"] or w["already_present"] or w["support_copied"]):
            print(f"  cowork from org {o['org']}: {verb} {w['copied']}, already present {w['already_present']}, "
                  f"retention -> {report['retention_days']}d on {w['retention_set']}, support {w['support_copied'] or '-'}")
            if w["cwd_inside_source"]:
                print(f"    keep the source folder: {w['cwd_inside_source']} session(s) still write outputs there")
    cli = report.get("cli_cleanup_period_days")
    if not isinstance(cli, int) or cli <= CLI_DEFAULT_RETENTION:
        print(f"  warning: CLI cleanupPeriodDays is {cli or 'unset'}; transcripts older than {CLI_DEFAULT_RETENTION} days get deleted")
    if report["mode"] == "plan":
        print("  plan only: re-run with --apply to write")
    else:
        print("  next: the app rescans within minutes; if the sidebar still lacks them, quit (Cmd+Q) and reopen."
              " Re-running the plan should show nothing left to copy")


# ---------- retention ----------

def cmd_retention(store: Store, args) -> dict:
    account = store.resolve_account(args.account)
    orgs = [args.org] if args.org else store.orgs(account)
    changed, total = 0, 0
    for org in orgs:
        for f in session_files(store.cowork_root / account / org):
            sdir = f.with_suffix("")
            if not sdir.is_dir():
                continue
            total += 1
            if ensure_retention(sdir, args.days, args.apply):
                changed += 1
    return {"mode": "apply" if args.apply else "plan", "account": account,
            "cowork_sessions": total, "retention_days": args.days, "updated": changed}


# ---------- entry ----------

def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--data-dir", help="Claude desktop data dir (default: macOS Application Support/Claude or $CLAUDE_DESKTOP_DATA_DIR)")
    ap.add_argument("--cli-dir", help="Claude Code config dir holding projects/ transcripts (default: $CLAUDE_CONFIG_DIR or ~/.claude)")
    ap.add_argument("--json", action="store_true", help="print machine-readable JSON")
    sub = ap.add_subparsers(dest="cmd", required=True)

    # Accept --json after the subcommand too; SUPPRESS keeps the global value when absent.
    common = argparse.ArgumentParser(add_help=False)
    common.add_argument("--json", action="store_true", default=argparse.SUPPRESS, help="print machine-readable JSON")

    sub.add_parser("scan", parents=[common], help="list accounts, orgs and session health")

    m = sub.add_parser("migrate", parents=[common], help="copy sessions from one account to another (plan unless --apply)")
    m.add_argument("--from", dest="source", required=True, help="source account: uuid, uuid prefix (8+), or email")
    m.add_argument("--to", dest="target", default="current", help="target account (default: the desktop app's current account)")
    m.add_argument("--from-org", help="only this source org (default: all)")
    m.add_argument("--to-org", help="target org (default: the target account's only org)")
    m.add_argument("--include-orphans", action="store_true", help="also copy Code sessions whose transcript is gone (title only)")
    m.add_argument("--no-code", action="store_true", help="skip Code-tab sessions")
    m.add_argument("--no-cowork", action="store_true", help="skip Cowork sessions")
    m.add_argument("--retention-days", type=int, default=DEFAULT_RETENTION, help=f"cleanupPeriodDays for copied Cowork sessions (default {DEFAULT_RETENTION})")
    m.add_argument("--apply", action="store_true", help="write changes; without it only the plan is printed")

    r = sub.add_parser("retention", parents=[common], help="raise cleanupPeriodDays inside Cowork sessions of one account")
    r.add_argument("--account", default="current")
    r.add_argument("--org")
    r.add_argument("--days", type=int, default=DEFAULT_RETENTION)
    r.add_argument("--apply", action="store_true")

    args = ap.parse_args(argv)
    data_dir = Path(args.data_dir).expanduser() if args.data_dir else default_data_dir()
    if not data_dir or not (data_dir / CODE_DIR).is_dir() and not (data_dir / COWORK_DIR).is_dir():
        raise SystemExit(f"error: no Claude desktop session store under {data_dir}; pass --data-dir")
    store = Store(data_dir, Path(args.cli_dir).expanduser() if args.cli_dir else default_cli_dir())

    if args.cmd == "scan":
        report = cmd_scan(store, args)
        print(json.dumps(report, ensure_ascii=False, indent=2)) if args.json else print_scan(report)
    elif args.cmd == "migrate":
        report = cmd_migrate(store, args)
        print(json.dumps(report, ensure_ascii=False, indent=2)) if args.json else print_migrate(report)
    else:
        report = cmd_retention(store, args)
        if args.json:
            print(json.dumps(report, ensure_ascii=False, indent=2))
        else:
            print(f"[{report['mode']}] account {report['account']}: {report['updated']} of "
                  f"{report['cowork_sessions']} Cowork sessions need cleanupPeriodDays >= {report['retention_days']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
